name: sparow_examples_dev
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pyomo
  - munch
  - numpy
  - glpk
  - flake8
  - pytest
  - pytest-cov
  - pip 
  - black 
  - pip:
    - mpi-sppy
