name: Pytest Tests

on:
  workflow_run:
    workflows: ["Auto Format Python Code"] # name of triggering workflow
    types:
      - completed

jobs:
  tests:
    if: ${{ github.event.workflow.run.conclusion == 'success' }}
    strategy:
      fail-fast: false  # If one job fails, the rest will still run
      matrix:
        os: [ubuntu-latest] # Omitting macos-latest because it is 10x more expensive
        python-version: ["3.10", "3.11", "3.12"] # removing 3.13 for now b/c haggis isn't supported
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      
      # Cache the conda environment
      - name: Cache conda environment
        uses: actions/cache@v4
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.conda
            ~/miniconda3/envs
          key: conda-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('dev_environment.yml') }}
          restore-keys: |
            conda-${{ matrix.os }}-${{ matrix.python-version }}-
            conda-${{ matrix.os }}-
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          activate-environment: conin_dev
          environment-file: dev_environment.yml
          use-mamba: true

      - name: Checkout or-topas
        uses: actions/checkout@v4
        with:
          repository: or-fusion/or_topas
          token: ${{ secrets.PAT_FOR_OR_TOPAS }}
          path: './or_topas'

      - name: Install or-topas
        run: |
            pip install ./or_topas
            rm -Rf ./or_topas

      - name: Checkout sparow
        uses: actions/checkout@v4
        with:
          repository: or-fusion/sparow
          token: ${{ secrets.PAT_FOR_OR_TOPAS }}
          path: './sparow'

      - name: Install sparow
        run: |
            pip install ./sparow
            rm -Rf ./sparow

      - name: Install package
        run: pip install -e .

      - name: Test with pytest
        run: pytest -v
